/// Offsets from now shown in the samples list. Negative values are future.
const samples = <(String, Duration)>[
  ('Just now', Duration(seconds: 5)),
  ('Seconds', Duration(seconds: 42)),
  ('A minute', Duration(seconds: 90)),
  ('Minutes', Duration(minutes: 25)),
  ('Hours', Duration(hours: 5)),
  ('A day', Duration(hours: 30)),
  ('Days', Duration(days: 4)),
  ('Weeks', Duration(days: 17)),
  ('Months', Duration(days: 95)),
  ('Years', Duration(days: 800)),
  ('In minutes', Duration(minutes: -12)),
  ('In days', Duration(days: -3)),
];

/// Display names for the bundled codes. Registered codes fall back to the code.
const localeNames = {
  'ar': 'Arabic',
  'de': 'German',
  'en': 'English',
  'es': 'Spanish',
  'fa': 'Persian',
  'fr': 'French',
  'hi': 'Hindi',
  'hr': 'Croatian',
  'id': 'Indonesian',
  'it': 'Italian',
  'ja': 'Japanese',
  'ko': 'Korean',
  'ne': 'Nepali',
  'nl': 'Dutch',
  'oc': 'Occitan',
  'pt': 'Portuguese (Brazil)',
  'ro': 'Romanian',
  'tr': 'Turkish',
  'ur': 'Urdu',
  'vi': 'Vietnamese',
  'zh': 'Chinese (Simplified)',
  'zh_TW': 'Chinese (Traditional)',
};
