// Regenerates lib/src/locales/cldr/*.g.dart from a pinned CLDR snapshot.
//
//   dart run tool/cldr/generate.dart           # from tool/cldr/48.2.2/
//   dart run tool/cldr/generate.dart --fetch   # download the snapshot first
import 'dart:convert';
import 'dart:io';

const version = '48.2.2';

/// Package locale code to CLDR locale id. `und` is CLDR's root, fetched only
/// so the parity test can prove `oc` is still placeholder data.
const cldrIds = {
  'ar': 'ar',
  'de': 'de',
  'en': 'en',
  'es': 'es',
  'fa': 'fa',
  'fr': 'fr',
  'hi': 'hi',
  'hr': 'hr',
  'id': 'id',
  'it': 'it',
  'ja': 'ja',
  'ko': 'ko',
  'ne': 'ne',
  'nl': 'nl',
  'oc': 'oc',
  'pt': 'pt',
  'ro': 'ro',
  'tr': 'tr',
  'ur': 'ur',
  'vi': 'vi',
  'zh': 'zh',
  'zh_TW': 'zh-Hant',
  'und': 'und',
};

/// No file is generated for these. CLDR's `oc` relative-time data is its root
/// locale's placeholders ("-{0} d"), checked 2026-09-27.
const skipped = {'oc', 'und'};

const units = ['second', 'minute', 'hour', 'day', 'week', 'month', 'year'];
const categories = ['zero', 'one', 'two', 'few', 'many', 'other'];
const styles = ['', '-short', '-narrow'];

/// Long-style units taken from CLDR; the rest keep 2.x's wording byte for byte.
List<String> longUnitsFor(String code) => switch (code) {
  'en' => const [], // house phrasing, "a week ago", for every unit
  'ar' || 'hr' => units, // ar: 2.x plurals were wrong from 11 up; hr: new
  _ => const ['week', 'month', 'year'],
};

/// Long future wording kept from 2.x where CLDR differs; only the plural nouns
/// were fixed.
const futureWording = {'ar': ('خلال', 'بعد')};

/// CLDR mistakes, fixed here so regeneration keeps the fix. Keyed like the
/// parity test's reasons; 49.0.0-BETA1 still has both.
const errata = {
  // "Within 3 months" for a past time: every other past form uses قبل.
  'ar month-short past few': 'قبل {0} أشهر',
  // The dual already says two; the long and narrow forms drop the count.
  'ar week-short future two': 'خلال أسبوعين',
};

Future<void> main(List<String> args) async {
  final snapshot = Directory('tool/cldr/$version');
  if (args.contains('--fetch')) await _fetch(snapshot);
  final out = Directory('lib/src/locales/cldr')..createSync(recursive: true);
  for (final code in cldrIds.keys.where((code) => !skipped.contains(code))) {
    final data =
        jsonDecode(File('${snapshot.path}/$code.json').readAsStringSync())
            as Map<String, dynamic>;
    File(
      '${out.path}/${code.toLowerCase()}.g.dart',
    ).writeAsStringSync(_library(code, data));
  }
  final format = Process.runSync('dart', ['format', out.path]);
  if (format.exitCode != 0) {
    throw ProcessException('dart', ['format'], '${format.stderr}');
  }
}

Future<void> _fetch(Directory snapshot) async {
  snapshot.createSync(recursive: true);
  final client = HttpClient();
  try {
    for (final MapEntry(key: code, value: id) in cldrIds.entries) {
      final uri = Uri.https(
        'raw.githubusercontent.com',
        '/unicode-org/cldr-json/$version/cldr-json/cldr-dates-full/main/$id/dateFields.json',
      );
      final response = await (await client.getUrl(uri)).close();
      if (response.statusCode != 200) {
        throw HttpException('${response.statusCode}', uri: uri);
      }
      final json =
          jsonDecode(await response.transform(utf8.decoder).join())
              as Map<String, dynamic>;
      final fields =
          json['main'][id]['dates']['fields'] as Map<String, dynamic>;
      final subset = {
        for (final unit in units)
          for (final suffix in styles) '$unit$suffix': fields['$unit$suffix'],
      };
      File('${snapshot.path}/$code.json').writeAsStringSync(
        '${const JsonEncoder.withIndent('  ').convert(subset)}\n',
      );
    }
  } finally {
    client.close();
  }
}

String _library(String code, Map<String, dynamic> data) {
  final name = code.replaceAllMapped(
    RegExp('_(.)(.*)'),
    (m) => m[1]!.toUpperCase() + m[2]!.toLowerCase(),
  );
  final long = longUnitsFor(code);
  final b = StringBuffer()
    ..writeln(
      '// Generated by tool/cldr/generate.dart from CLDR $version. Do not edit.',
    )
    ..writeln('// ignore_for_file: public_member_api_docs')
    ..writeln()
    ..writeln("import '../../messages/time_ago_locale.dart';")
    ..writeln("import '../../time_unit.dart';")
    ..writeln();
  if (long.length == units.length) {
    b.writeln('const ${name}Long = ${_patterns(code, data, '')};');
  } else if (long.isNotEmpty) {
    b.writeln(
      'const ${name}LongUnits = <TimeUnit, RelativePatterns>{'
      '${_units(code, data, '', long)}};',
    );
  }
  b
    ..writeln('const ${name}Short = ${_patterns(code, data, '-short')};')
    ..writeln('const ${name}Narrow = ${_patterns(code, data, '-narrow')};');
  return b.toString();
}

String _patterns(String code, Map<String, dynamic> data, String suffix) =>
    'TimeAgoPatterns(justNow: '
    '${_lit(data['second$suffix']['relative-type-0'] as String)}, '
    'units: {${_units(code, data, suffix, units)}})';

String _units(
  String code,
  Map<String, dynamic> data,
  String suffix,
  List<String> which,
) => [
  for (final unit in which)
    'TimeUnit.$unit: RelativePatterns('
        'past: ${_plural('$code $unit$suffix past', data['$unit$suffix']['relativeTime-type-past'] as Map<String, dynamic>, null)}, '
        'future: ${_plural('$code $unit$suffix future', data['$unit$suffix']['relativeTime-type-future'] as Map<String, dynamic>, suffix.isEmpty ? futureWording[code] : null)}),',
].join();

String _plural(
  String where,
  Map<String, dynamic> forms,
  (String, String)? wording,
) {
  String pattern(String category) {
    final raw = forms['relativeTimePattern-count-$category'] as String;
    return _lit(
      errata['$where $category'] ??
          (wording == null ? raw : raw.replaceAll(wording.$1, wording.$2)),
    );
  }

  final fields = [
    for (final category in categories)
      if (forms.containsKey('relativeTimePattern-count-$category'))
        '$category: ${pattern(category)}',
  ];
  return 'Plural(${fields.join(', ')})';
}

/// A single-quoted Dart literal. Invisible and bidi characters are escaped so
/// a reviewer can see them.
String _lit(String text) {
  final b = StringBuffer("'");
  for (final rune in text.runes) {
    b.write(switch (rune) {
      0x5C => r'\\',
      0x27 => r"\'",
      0x24 => r'\$',
      < 0x20 ||
      0xA0 ||
      0x202F ||
      (>= 0x200B && <= 0x200F) ||
      (>= 0x202A && <= 0x202E) ||
      (>= 0x2066 && <= 0x2069) => '\\u{${rune.toRadixString(16)}}',
      _ => String.fromCharCode(rune),
    });
  }
  return (b..write("'")).toString();
}
