// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const deLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: 'vor {0} Woche', other: 'vor {0} Wochen'),
    future: Plural(one: 'in {0} Woche', other: 'in {0} Wochen'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: 'vor {0} Monat', other: 'vor {0} Monaten'),
    future: Plural(one: 'in {0} Monat', other: 'in {0} Monaten'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: 'vor {0} Jahr', other: 'vor {0} Jahren'),
    future: Plural(one: 'in {0} Jahr', other: 'in {0} Jahren'),
  ),
};
const deShort = TimeAgoPatterns(
  justNow: 'jetzt',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: 'vor {0} Sek.', other: 'vor {0} Sek.'),
      future: Plural(one: 'in {0} Sek.', other: 'in {0} Sek.'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: 'vor {0} Min.', other: 'vor {0} Min.'),
      future: Plural(one: 'in {0} Min.', other: 'in {0} Min.'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: 'vor {0} Std.', other: 'vor {0} Std.'),
      future: Plural(one: 'in {0} Std.', other: 'in {0} Std.'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: 'vor {0} Tag', other: 'vor {0} Tagen'),
      future: Plural(one: 'in {0} Tag', other: 'in {0} Tagen'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: 'vor {0} Woche', other: 'vor {0} Wochen'),
      future: Plural(one: 'in {0} Woche', other: 'in {0} Wochen'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: 'vor {0} Monat', other: 'vor {0}\u{a0}Monaten'),
      future: Plural(one: 'in {0} Monat', other: 'in {0} Monaten'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: 'vor {0} Jahr', other: 'vor {0} Jahren'),
      future: Plural(one: 'in {0} Jahr', other: 'in {0} Jahren'),
    ),
  },
);
const deNarrow = TimeAgoPatterns(
  justNow: 'jetzt',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: 'vor {0} s', other: 'vor {0} s'),
      future: Plural(one: 'in {0} s', other: 'in {0} s'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: 'vor {0} m', other: 'vor {0} m'),
      future: Plural(one: 'in {0} m', other: 'in {0} m'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: 'vor {0} Std.', other: 'vor {0} Std.'),
      future: Plural(one: 'in {0} Std.', other: 'in {0} Std.'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: 'vor {0} Tag', other: 'vor {0} Tagen'),
      future: Plural(one: 'in {0} Tag', other: 'in {0} Tagen'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: 'vor {0} Wo.', other: 'vor {0} Wo.'),
      future: Plural(one: 'in {0} Wo.', other: 'in {0} Wo.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: 'vor {0}\u{a0}Monat', other: 'vor {0} Monaten'),
      future: Plural(one: 'in {0} Monat', other: 'in {0} Monaten'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: 'vor {0} Jahr', other: 'vor {0} Jahren'),
      future: Plural(one: 'in {0} Jahr', other: 'in {0} Jahren'),
    ),
  },
);
