// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const enShort = TimeAgoPatterns(
  justNow: 'now',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} sec. ago', other: '{0} sec. ago'),
      future: Plural(one: 'in {0} sec.', other: 'in {0} sec.'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} min. ago', other: '{0} min. ago'),
      future: Plural(one: 'in {0} min.', other: 'in {0} min.'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} hr. ago', other: '{0} hr. ago'),
      future: Plural(one: 'in {0} hr.', other: 'in {0} hr.'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} day ago', other: '{0} days ago'),
      future: Plural(one: 'in {0} day', other: 'in {0} days'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} wk. ago', other: '{0} wk. ago'),
      future: Plural(one: 'in {0} wk.', other: 'in {0} wk.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} mo. ago', other: '{0} mo. ago'),
      future: Plural(one: 'in {0} mo.', other: 'in {0} mo.'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} yr. ago', other: '{0} yr. ago'),
      future: Plural(one: 'in {0} yr.', other: 'in {0} yr.'),
    ),
  },
);
const enNarrow = TimeAgoPatterns(
  justNow: 'now',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0}s ago', other: '{0}s ago'),
      future: Plural(one: 'in {0}s', other: 'in {0}s'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0}m ago', other: '{0}m ago'),
      future: Plural(one: 'in {0}m', other: 'in {0}m'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0}h ago', other: '{0}h ago'),
      future: Plural(one: 'in {0}h', other: 'in {0}h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0}d ago', other: '{0}d ago'),
      future: Plural(one: 'in {0}d', other: 'in {0}d'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0}w ago', other: '{0}w ago'),
      future: Plural(one: 'in {0}w', other: 'in {0}w'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0}mo ago', other: '{0}mo ago'),
      future: Plural(one: 'in {0}mo', other: 'in {0}mo'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0}y ago', other: '{0}y ago'),
      future: Plural(one: 'in {0}y', other: 'in {0}y'),
    ),
  },
);
