// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const esLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: 'hace {0} semana', other: 'hace {0} semanas'),
    future: Plural(one: 'dentro de {0} semana', other: 'dentro de {0} semanas'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: 'hace {0} mes', other: 'hace {0} meses'),
    future: Plural(one: 'dentro de {0} mes', other: 'dentro de {0} meses'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: 'hace {0} año', other: 'hace {0} años'),
    future: Plural(one: 'dentro de {0} año', other: 'dentro de {0} años'),
  ),
};
const esShort = TimeAgoPatterns(
  justNow: 'ahora',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: 'hace {0} s', other: 'hace {0} s'),
      future: Plural(one: 'dentro de {0} s', other: 'dentro de {0} s'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: 'hace {0} min', other: 'hace {0} min'),
      future: Plural(one: 'dentro de {0} min', other: 'dentro de {0} min'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: 'hace {0} h', other: 'hace {0} h'),
      future: Plural(one: 'dentro de {0} h', other: 'dentro de {0} h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: 'hace {0} d', other: 'hace {0} d'),
      future: Plural(one: 'dentro de {0} d', other: 'dentro de {0} d'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: 'hace {0} sem.', other: 'hace {0} sem.'),
      future: Plural(one: 'dentro de {0} sem.', other: 'dentro de {0} sem.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: 'hace {0} m', other: 'hace {0} m'),
      future: Plural(one: 'dentro de {0} m', other: 'dentro de {0} m'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: 'hace {0} a', other: 'hace {0} a'),
      future: Plural(one: 'dentro de {0} a', other: 'dentro de {0} a'),
    ),
  },
);
const esNarrow = TimeAgoPatterns(
  justNow: 'ahora',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: 'hace {0} s', other: 'hace {0} s'),
      future: Plural(one: 'dentro de {0} s', other: 'dentro de {0} s'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: 'hace {0} min', other: 'hace {0} min'),
      future: Plural(one: 'dentro de {0} min', other: 'dentro de {0} min'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: 'hace {0} h', other: 'hace {0} h'),
      future: Plural(one: 'dentro de {0} h', other: 'dentro de {0} h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: 'hace {0} d', other: 'hace {0} d'),
      future: Plural(one: 'dentro de {0} d', other: 'dentro de {0} d'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: 'hace {0} sem.', other: 'hace {0} sem.'),
      future: Plural(one: 'dentro de {0} sem.', other: 'dentro de {0} sem.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: 'hace {0} m', other: 'hace {0} m'),
      future: Plural(one: 'dentro de {0} m', other: 'dentro de {0} m'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: 'hace {0} a', other: 'hace {0} a'),
      future: Plural(one: 'dentro de {0} a', other: 'dentro de {0} a'),
    ),
  },
);
