// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const faLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: '{0} هفته پیش', other: '{0} هفته پیش'),
    future: Plural(one: '{0} هفته بعد', other: '{0} هفته بعد'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: '{0} ماه پیش', other: '{0} ماه پیش'),
    future: Plural(one: '{0} ماه بعد', other: '{0} ماه بعد'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: '{0} سال پیش', other: '{0} سال پیش'),
    future: Plural(one: '{0} سال بعد', other: '{0} سال بعد'),
  ),
};
const faShort = TimeAgoPatterns(
  justNow: 'اکنون',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} ثانیه پیش', other: '{0} ثانیه پیش'),
      future: Plural(one: '{0} ثانیه بعد', other: '{0} ثانیه بعد'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} دقیقه پیش', other: '{0} دقیقه پیش'),
      future: Plural(one: '{0} دقیقه بعد', other: '{0} دقیقه بعد'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} ساعت پیش', other: '{0} ساعت پیش'),
      future: Plural(one: '{0} ساعت بعد', other: '{0} ساعت بعد'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} روز پیش', other: '{0} روز پیش'),
      future: Plural(one: '{0} روز دیگر', other: '{0} روز دیگر'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} هفته پیش', other: '{0} هفته پیش'),
      future: Plural(one: '{0} هفته بعد', other: '{0} هفته بعد'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} ماه پیش', other: '{0} ماه پیش'),
      future: Plural(one: '{0} ماه بعد', other: '{0} ماه بعد'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} سال پیش', other: '{0} سال پیش'),
      future: Plural(one: '{0} سال بعد', other: '{0} سال بعد'),
    ),
  },
);
const faNarrow = TimeAgoPatterns(
  justNow: 'اکنون',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} ثانیه پیش', other: '{0} ثانیه پیش'),
      future: Plural(one: '{0} ثانیه بعد', other: '{0} ثانیه بعد'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} دقیقه پیش', other: '{0} دقیقه پیش'),
      future: Plural(one: '{0} دقیقه بعد', other: '{0} دقیقه بعد'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} ساعت پیش', other: '{0} ساعت پیش'),
      future: Plural(one: '{0} ساعت بعد', other: '{0} ساعت بعد'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} روز پیش', other: '{0} روز پیش'),
      future: Plural(one: '{0} روز بعد', other: '{0} روز بعد'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} هفته پیش', other: '{0} هفته پیش'),
      future: Plural(one: '{0} هفته بعد', other: '{0} هفته بعد'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} ماه پیش', other: '{0} ماه پیش'),
      future: Plural(one: '{0} ماه بعد', other: '{0} ماه بعد'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} سال پیش', other: '{0} سال پیش'),
      future: Plural(one: '{0} سال بعد', other: '{0} سال بعد'),
    ),
  },
);
