// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const frLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: 'il y a {0} semaine', other: 'il y a {0} semaines'),
    future: Plural(one: 'dans {0} semaine', other: 'dans {0} semaines'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: 'il y a {0} mois', other: 'il y a {0} mois'),
    future: Plural(one: 'dans {0} mois', other: 'dans {0} mois'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: 'il y a {0} an', other: 'il y a {0} ans'),
    future: Plural(one: 'dans {0} an', other: 'dans {0} ans'),
  ),
};
const frShort = TimeAgoPatterns(
  justNow: 'maintenant',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: 'il y a {0}\u{a0}s', other: 'il y a {0}\u{a0}s'),
      future: Plural(one: 'dans {0}\u{a0}s', other: 'dans {0}\u{a0}s'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: 'il y a {0}\u{a0}min', other: 'il y a {0}\u{a0}min'),
      future: Plural(one: 'dans {0}\u{a0}min', other: 'dans {0}\u{a0}min'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: 'il y a {0}\u{a0}h', other: 'il y a {0}\u{a0}h'),
      future: Plural(one: 'dans {0}\u{a0}h', other: 'dans {0}\u{a0}h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: 'il y a {0}\u{a0}j', other: 'il y a {0}\u{a0}j'),
      future: Plural(one: 'dans {0}\u{a0}j', other: 'dans {0}\u{a0}j'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: 'il y a {0} sem.', other: 'il y a {0} sem.'),
      future: Plural(one: 'dans {0} sem.', other: 'dans {0} sem.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: 'il y a {0} m.', other: 'il y a {0} m.'),
      future: Plural(one: 'dans {0} m.', other: 'dans {0} m.'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: 'il y a {0} a', other: 'il y a {0} a'),
      future: Plural(one: 'dans {0} a', other: 'dans {0} a'),
    ),
  },
);
const frNarrow = TimeAgoPatterns(
  justNow: 'maintenant',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '-{0} s', other: '-{0} s'),
      future: Plural(one: '+{0} s', other: '+{0} s'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '-{0} min', other: '-{0} min'),
      future: Plural(one: '+{0} min', other: '+{0} min'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '-{0} h', other: '-{0} h'),
      future: Plural(one: '+{0} h', other: '+{0} h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '-{0} j', other: '-{0} j'),
      future: Plural(one: '+{0} j', other: '+{0} j'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '-{0} sem.', other: '-{0} sem.'),
      future: Plural(one: '+{0} sem.', other: '+{0} sem.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '-{0} m.', other: '-{0} m.'),
      future: Plural(one: '+{0} m.', other: '+{0} m.'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '-{0} a', other: '-{0} a'),
      future: Plural(one: '+{0} a', other: '+{0} a'),
    ),
  },
);
