// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const hiLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: '{0} सप्ताह पहले', other: '{0} सप्ताह पहले'),
    future: Plural(one: '{0} सप्ताह में', other: '{0} सप्ताह में'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: '{0} माह पहले', other: '{0} माह पहले'),
    future: Plural(one: '{0} माह में', other: '{0} माह में'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: '{0} वर्ष पहले', other: '{0} वर्ष पहले'),
    future: Plural(one: '{0} वर्ष में', other: '{0} वर्ष में'),
  ),
};
const hiShort = TimeAgoPatterns(
  justNow: 'अब',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} से॰ पहले', other: '{0} से॰ पहले'),
      future: Plural(one: '{0} से॰ में', other: '{0} से॰ में'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} मि॰ पहले', other: '{0} मि॰ पहले'),
      future: Plural(one: '{0} मि॰ में', other: '{0} मि॰ में'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} घं॰ पहले', other: '{0} घं॰ पहले'),
      future: Plural(one: '{0} घं॰ में', other: '{0} घं॰ में'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} दिन पहले', other: '{0} दिन पहले'),
      future: Plural(one: '{0} दिन में', other: '{0} दिन में'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} सप्ताह पहले', other: '{0} सप्ताह पहले'),
      future: Plural(one: '{0} सप्ताह में', other: '{0} सप्ताह में'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} माह पहले', other: '{0} माह पहले'),
      future: Plural(one: '{0} माह में', other: '{0} माह में'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} वर्ष पहले', other: '{0} वर्ष पहले'),
      future: Plural(one: '{0} वर्ष में', other: '{0} वर्ष में'),
    ),
  },
);
const hiNarrow = TimeAgoPatterns(
  justNow: 'अब',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} से॰ पहले', other: '{0} से॰ पहले'),
      future: Plural(one: '{0} से॰ में', other: '{0} से॰ में'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} मि॰ पहले', other: '{0} मि॰ पहले'),
      future: Plural(one: '{0} मि॰ में', other: '{0} मि॰ में'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} घं॰ पहले', other: '{0} घं॰ पहले'),
      future: Plural(one: '{0} घं॰ में', other: '{0} घं॰ में'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} दिन पहले', other: '{0} दिन पहले'),
      future: Plural(one: '{0} दिन में', other: '{0} दिन में'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} सप्ताह पहले', other: '{0} सप्ताह पहले'),
      future: Plural(one: '{0} सप्ताह में', other: '{0} सप्ताह में'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} माह पहले', other: '{0} माह पहले'),
      future: Plural(one: '{0} माह में', other: '{0} माह में'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} वर्ष पहले', other: '{0} वर्ष पहले'),
      future: Plural(one: '{0} वर्ष में', other: '{0} वर्ष में'),
    ),
  },
);
