// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const hrLong = TimeAgoPatterns(
  justNow: 'sad',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(
        one: 'prije {0} sekundu',
        few: 'prije {0} sekunde',
        other: 'prije {0} sekundi',
      ),
      future: Plural(
        one: 'za {0} sekundu',
        few: 'za {0} sekunde',
        other: 'za {0} sekundi',
      ),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(
        one: 'prije {0} minutu',
        few: 'prije {0} minute',
        other: 'prije {0} minuta',
      ),
      future: Plural(
        one: 'za {0} minutu',
        few: 'za {0} minute',
        other: 'za {0} minuta',
      ),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(
        one: 'prije {0} sat',
        few: 'prije {0} sata',
        other: 'prije {0} sati',
      ),
      future: Plural(
        one: 'za {0} sat',
        few: 'za {0} sata',
        other: 'za {0} sati',
      ),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(
        one: 'prije {0} dan',
        few: 'prije {0} dana',
        other: 'prije {0} dana',
      ),
      future: Plural(
        one: 'za {0} dan',
        few: 'za {0} dana',
        other: 'za {0} dana',
      ),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(
        one: 'prije {0} tjedan',
        few: 'prije {0} tjedna',
        other: 'prije {0} tjedana',
      ),
      future: Plural(
        one: 'za {0} tjedan',
        few: 'za {0} tjedna',
        other: 'za {0} tjedana',
      ),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(
        one: 'prije {0} mjesec',
        few: 'prije {0} mjeseca',
        other: 'prije {0} mjeseci',
      ),
      future: Plural(
        one: 'za {0} mjesec',
        few: 'za {0} mjeseca',
        other: 'za {0} mjeseci',
      ),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(
        one: 'prije {0} godinu',
        few: 'prije {0} godine',
        other: 'prije {0} godina',
      ),
      future: Plural(
        one: 'za {0} godinu',
        few: 'za {0} godine',
        other: 'za {0} godina',
      ),
    ),
  },
);
const hrShort = TimeAgoPatterns(
  justNow: 'sad',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(
        one: 'prije {0} s',
        few: 'prije {0} s',
        other: 'prije {0} s',
      ),
      future: Plural(one: 'za {0} s', few: 'za {0} s', other: 'za {0} s'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(
        one: 'prije {0} min',
        few: 'prije {0} min',
        other: 'prije {0} min',
      ),
      future: Plural(one: 'za {0} min', few: 'za {0} min', other: 'za {0} min'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(
        one: 'prije {0} h',
        few: 'prije {0} h',
        other: 'prije {0} h',
      ),
      future: Plural(one: 'za {0} h', few: 'za {0} h', other: 'za {0} h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(
        one: 'prije {0} dan',
        few: 'prije {0} dana',
        other: 'prije {0} dana',
      ),
      future: Plural(
        one: 'za {0} dan',
        few: 'za {0} dana',
        other: 'za {0} dana',
      ),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(
        one: 'prije {0} tj.',
        few: 'prije {0} tj.',
        other: 'prije {0} tj.',
      ),
      future: Plural(one: 'za {0} tj.', few: 'za {0} tj.', other: 'za {0} tj.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(
        one: 'prije {0} mj.',
        few: 'prije {0} mj.',
        other: 'prije {0} mj.',
      ),
      future: Plural(one: 'za {0} mj.', few: 'za {0} mj.', other: 'za {0} mj.'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(
        one: 'prije {0} g.',
        few: 'prije {0} g.',
        other: 'prije {0} g.',
      ),
      future: Plural(one: 'za {0} g.', few: 'za {0} g.', other: 'za {0} g.'),
    ),
  },
);
const hrNarrow = TimeAgoPatterns(
  justNow: 'sad',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(
        one: 'prije {0} s',
        few: 'prije {0} s',
        other: 'prije {0} s',
      ),
      future: Plural(one: 'za {0} s', few: 'za {0} s', other: 'za {0} s'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(
        one: 'prije {0} min',
        few: 'prije {0} min',
        other: 'prije {0} min',
      ),
      future: Plural(one: 'za {0} min', few: 'za {0} min', other: 'za {0} min'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(
        one: 'prije {0} h',
        few: 'prije {0} h',
        other: 'prije {0} h',
      ),
      future: Plural(one: 'za {0} h', few: 'za {0} h', other: 'za {0} h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(
        one: 'prije {0} d',
        few: 'prije {0} d',
        other: 'prije {0} d',
      ),
      future: Plural(one: 'za {0} d', few: 'za {0} d', other: 'za {0} d'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(
        one: 'prije {0} tj.',
        few: 'prije {0} tj.',
        other: 'prije {0} tj.',
      ),
      future: Plural(one: 'za {0} tj.', few: 'za {0} tj.', other: 'za {0} tj.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(
        one: 'prije {0} mj.',
        few: 'prije {0} mj.',
        other: 'prije {0} mj.',
      ),
      future: Plural(one: 'za {0} mj.', few: 'za {0} mj.', other: 'za {0} mj.'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(
        one: 'prije {0} g.',
        few: 'prije {0} g.',
        other: 'prije {0} g.',
      ),
      future: Plural(one: 'za {0} g.', few: 'za {0} g.', other: 'za {0} g.'),
    ),
  },
);
