// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const idLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(other: '{0} minggu yang lalu'),
    future: Plural(other: 'dalam {0} minggu'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(other: '{0} bulan yang lalu'),
    future: Plural(other: 'dalam {0} bulan'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(other: '{0} tahun yang lalu'),
    future: Plural(other: 'dalam {0} tahun'),
  ),
};
const idShort = TimeAgoPatterns(
  justNow: 'sekarang',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0} dtk lalu'),
      future: Plural(other: 'dlm {0} dtk'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0} mnt lalu'),
      future: Plural(other: 'dlm {0} mnt'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0} jam lalu'),
      future: Plural(other: 'dalam {0} jam'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0} h lalu'),
      future: Plural(other: 'dalam {0} h'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0} mgg lalu'),
      future: Plural(other: 'dlm {0} mgg'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0} bln lalu'),
      future: Plural(other: 'dlm {0} bln'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0} thn lalu'),
      future: Plural(other: 'dlm {0} thn'),
    ),
  },
);
const idNarrow = TimeAgoPatterns(
  justNow: 'sekarang',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0} dtk lalu'),
      future: Plural(other: 'dlm {0} dtk'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0} mnt lalu'),
      future: Plural(other: 'dlm {0} mnt'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0} jam lalu'),
      future: Plural(other: 'dlm {0} jam'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0} h lalu'),
      future: Plural(other: 'dalam {0} h'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0} mgg lalu'),
      future: Plural(other: 'dlm {0} mgg'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0} bln lalu'),
      future: Plural(other: 'dlm {0} bln'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0} thn lalu'),
      future: Plural(other: 'dlm {0} thn'),
    ),
  },
);
