// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const itLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: '{0} settimana fa', other: '{0} settimane fa'),
    future: Plural(one: 'tra {0} settimana', other: 'tra {0} settimane'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: '{0} mese fa', other: '{0} mesi fa'),
    future: Plural(one: 'tra {0} mese', other: 'tra {0} mesi'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: '{0} anno fa', other: '{0} anni fa'),
    future: Plural(one: 'tra {0} anno', other: 'tra {0} anni'),
  ),
};
const itShort = TimeAgoPatterns(
  justNow: 'ora',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} sec. fa', other: '{0} sec. fa'),
      future: Plural(one: 'tra {0} sec.', other: 'tra {0} sec.'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} min fa', other: '{0} min fa'),
      future: Plural(one: 'tra {0} min', other: 'tra {0} min'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} h fa', other: '{0} h fa'),
      future: Plural(one: 'tra {0} h', other: 'tra {0} h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} g fa', other: '{0} gg fa'),
      future: Plural(one: 'tra {0} g', other: 'tra {0} gg'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} sett. fa', other: '{0} sett. fa'),
      future: Plural(one: 'tra {0} sett.', other: 'tra {0} sett.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} mese fa', other: '{0} mesi fa'),
      future: Plural(one: 'tra {0} mese', other: 'tra {0} mesi'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} anno fa', other: '{0} anni fa'),
      future: Plural(one: 'tra {0} anno', other: 'tra {0} anni'),
    ),
  },
);
const itNarrow = TimeAgoPatterns(
  justNow: 'ora',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} s fa', other: '{0} s fa'),
      future: Plural(one: 'tra {0} s', other: 'tra {0} s'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} min fa', other: '{0} min fa'),
      future: Plural(one: 'tra {0} min', other: 'tra {0} min'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} h fa', other: '{0} h fa'),
      future: Plural(one: 'tra {0} h', other: 'tra {0} h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} g fa', other: '{0} gg fa'),
      future: Plural(one: 'tra {0} g', other: 'tra {0} gg'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} sett. fa', other: '{0} sett. fa'),
      future: Plural(one: 'tra {0} sett.', other: 'tra {0} sett.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} mese fa', other: '{0} mesi fa'),
      future: Plural(one: 'tra {0} mese', other: 'tra {0} mesi'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} anno fa', other: '{0} anni fa'),
      future: Plural(one: 'tra {0} anno', other: 'tra {0} anni'),
    ),
  },
);
