// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const jaLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(other: '{0} 週間前'),
    future: Plural(other: '{0} 週間後'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(other: '{0} か月前'),
    future: Plural(other: '{0} か月後'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(other: '{0} 年前'),
    future: Plural(other: '{0} 年後'),
  ),
};
const jaShort = TimeAgoPatterns(
  justNow: '今',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0} 秒前'),
      future: Plural(other: '{0} 秒後'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0} 分前'),
      future: Plural(other: '{0} 分後'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0} 時間前'),
      future: Plural(other: '{0} 時間後'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0} 日前'),
      future: Plural(other: '{0} 日後'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0} 週間前'),
      future: Plural(other: '{0} 週間後'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0} か月前'),
      future: Plural(other: '{0} か月後'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0} 年前'),
      future: Plural(other: '{0} 年後'),
    ),
  },
);
const jaNarrow = TimeAgoPatterns(
  justNow: '今',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0}秒前'),
      future: Plural(other: '{0}秒後'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0}分前'),
      future: Plural(other: '{0}分後'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0}時間前'),
      future: Plural(other: '{0}時間後'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0}日前'),
      future: Plural(other: '{0}日後'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0}週間前'),
      future: Plural(other: '{0}週間後'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0}か月前'),
      future: Plural(other: '{0}か月後'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0}年前'),
      future: Plural(other: '{0}年後'),
    ),
  },
);
