// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const koLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(other: '{0}주 전'),
    future: Plural(other: '{0}주 후'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(other: '{0}개월 전'),
    future: Plural(other: '{0}개월 후'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(other: '{0}년 전'),
    future: Plural(other: '{0}년 후'),
  ),
};
const koShort = TimeAgoPatterns(
  justNow: '지금',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0}초 전'),
      future: Plural(other: '{0}초 후'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0}분 전'),
      future: Plural(other: '{0}분 후'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0}시간 전'),
      future: Plural(other: '{0}시간 후'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0}일 전'),
      future: Plural(other: '{0}일 후'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0}주 전'),
      future: Plural(other: '{0}주 후'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0}개월 전'),
      future: Plural(other: '{0}개월 후'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0}년 전'),
      future: Plural(other: '{0}년 후'),
    ),
  },
);
const koNarrow = TimeAgoPatterns(
  justNow: '지금',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0}초 전'),
      future: Plural(other: '{0}초 후'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0}분 전'),
      future: Plural(other: '{0}분 후'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0}시간 전'),
      future: Plural(other: '{0}시간 후'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0}일 전'),
      future: Plural(other: '{0}일 후'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0}주 전'),
      future: Plural(other: '{0}주 후'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0}개월 전'),
      future: Plural(other: '{0}개월 후'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0}년 전'),
      future: Plural(other: '{0}년 후'),
    ),
  },
);
