// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const neLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: '{0} हप्ता पहिले', other: '{0} हप्ता पहिले'),
    future: Plural(one: '{0} हप्तामा', other: '{0} हप्तामा'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: '{0} महिना पहिले', other: '{0} महिना पहिले'),
    future: Plural(one: '{0} महिनामा', other: '{0} महिनामा'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: '{0} वर्ष अघि', other: '{0} वर्ष अघि'),
    future: Plural(one: '{0} वर्षमा', other: '{0} वर्षमा'),
  ),
};
const neShort = TimeAgoPatterns(
  justNow: 'अहिले',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} सेकेन्ड पहिले', other: '{0} सेकेन्ड पहिले'),
      future: Plural(one: '{0} सेकेन्डमा', other: '{0} सेकेन्डमा'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} मिनेट पहिले', other: '{0} मिनेट पहिले'),
      future: Plural(one: '{0} मिनेटमा', other: '{0} मिनेटमा'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} घण्टा पहिले', other: '{0} घण्टा पहिले'),
      future: Plural(one: '{0} घण्टामा', other: '{0} घण्टामा'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} दिन पहिले', other: '{0} दिन पहिले'),
      future: Plural(one: '{0} दिनमा', other: '{0} दिनमा'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} हप्ता पहिले', other: '{0} हप्ता पहिले'),
      future: Plural(one: '{0} हप्तामा', other: '{0} हप्तामा'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} महिना पहिले', other: '{0} महिना पहिले'),
      future: Plural(one: '{0} महिनामा', other: '{0} महिनामा'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} वर्ष अघि', other: '{0} वर्ष अघि'),
      future: Plural(one: '{0} वर्षमा', other: '{0} वर्षमा'),
    ),
  },
);
const neNarrow = TimeAgoPatterns(
  justNow: 'अहिले',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} सेकेन्ड पहिले', other: '{0} सेकेन्ड पहिले'),
      future: Plural(one: '{0} सेकेन्डमा', other: '{0} सेकेन्डमा'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} मिनेट पहिले', other: '{0} मिनेट पहिले'),
      future: Plural(one: '{0} मिनेटमा', other: '{0} मिनेटमा'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} घण्टा पहिले', other: '{0} घण्टा पहिले'),
      future: Plural(one: '{0} घण्टामा', other: '{0} घण्टामा'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} दिन पहिले', other: '{0} दिन पहिले'),
      future: Plural(one: '{0} दिनमा', other: '{0} दिनमा'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} हप्ता पहिले', other: '{0} हप्ता पहिले'),
      future: Plural(one: '{0} हप्तामा', other: '{0} हप्तामा'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} महिना पहिले', other: '{0} महिना पहिले'),
      future: Plural(one: '{0} महिनामा', other: '{0} महिनामा'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} वर्ष अघि', other: '{0} वर्ष अघि'),
      future: Plural(one: '{0} वर्षमा', other: '{0} वर्षमा'),
    ),
  },
);
