// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const nlLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: '{0} week geleden', other: '{0} weken geleden'),
    future: Plural(one: 'over {0} week', other: 'over {0} weken'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: '{0} maand geleden', other: '{0} maanden geleden'),
    future: Plural(one: 'over {0} maand', other: 'over {0} maanden'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: '{0} jaar geleden', other: '{0} jaar geleden'),
    future: Plural(one: 'over {0} jaar', other: 'over {0} jaar'),
  ),
};
const nlShort = TimeAgoPatterns(
  justNow: 'nu',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} sec. geleden', other: '{0} sec. geleden'),
      future: Plural(one: 'over {0} sec.', other: 'over {0} sec.'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} min. geleden', other: '{0} min. geleden'),
      future: Plural(one: 'over {0} min.', other: 'over {0} min.'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} uur geleden', other: '{0} uur geleden'),
      future: Plural(one: 'over {0} uur', other: 'over {0} uur'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} dag geleden', other: '{0} dgn geleden'),
      future: Plural(one: 'over {0} dag', other: 'over {0} dgn'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} week geleden', other: '{0} weken geleden'),
      future: Plural(one: 'over {0} week', other: 'over {0} weken'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} maand geleden', other: '{0} maanden geleden'),
      future: Plural(one: 'over {0} maand', other: 'over {0} maanden'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} jaar geleden', other: '{0} jaar geleden'),
      future: Plural(one: 'over {0} jaar', other: 'over {0} jaar'),
    ),
  },
);
const nlNarrow = TimeAgoPatterns(
  justNow: 'nu',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} sec. geleden', other: '{0} sec. geleden'),
      future: Plural(one: 'over {0} sec.', other: 'over {0} sec.'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} min. geleden', other: '{0} min. geleden'),
      future: Plural(one: 'over {0} min.', other: 'over {0} min.'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} uur geleden', other: '{0} uur geleden'),
      future: Plural(one: 'over {0} uur', other: 'over {0} uur'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} dag geleden', other: '{0} dgn geleden'),
      future: Plural(one: 'over {0} dag', other: 'over {0} dgn'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} week geleden', other: '{0} weken geleden'),
      future: Plural(one: 'over {0} week', other: 'over {0} weken'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} maand geleden', other: '{0} maanden geleden'),
      future: Plural(one: 'over {0} maand', other: 'over {0} maanden'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} jaar geleden', other: '{0} jaar geleden'),
      future: Plural(one: 'over {0} jaar', other: 'over {0} jaar'),
    ),
  },
);
