// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const ptLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: 'há {0} semana', other: 'há {0} semanas'),
    future: Plural(one: 'em {0} semana', other: 'em {0} semanas'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: 'há {0} mês', other: 'há {0} meses'),
    future: Plural(one: 'em {0} mês', other: 'em {0} meses'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: 'há {0} ano', other: 'há {0} anos'),
    future: Plural(one: 'em {0} ano', other: 'em {0} anos'),
  ),
};
const ptShort = TimeAgoPatterns(
  justNow: 'agora',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: 'há {0} seg.', other: 'há {0} seg.'),
      future: Plural(one: 'em {0} seg.', other: 'em {0} seg.'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: 'há {0} min.', other: 'há {0} min.'),
      future: Plural(one: 'em {0} min.', other: 'em {0} min.'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: 'há {0} h', other: 'há {0} h'),
      future: Plural(one: 'em {0} h', other: 'em {0} h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: 'há {0} dia', other: 'há {0} dias'),
      future: Plural(one: 'em {0} dia', other: 'em {0} dias'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: 'há {0} sem.', other: 'há {0} sem.'),
      future: Plural(one: 'em {0} sem.', other: 'em {0} sem.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: 'há {0} mês', other: 'há {0} meses'),
      future: Plural(one: 'em {0} mês', other: 'em {0} meses'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: 'há {0} ano', other: 'há {0} anos'),
      future: Plural(one: 'em {0} ano', other: 'em {0} anos'),
    ),
  },
);
const ptNarrow = TimeAgoPatterns(
  justNow: 'agora',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: 'há {0} seg.', other: 'há {0} seg.'),
      future: Plural(one: 'em {0} seg.', other: 'em {0} seg.'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: 'há {0} min.', other: 'há {0} min.'),
      future: Plural(one: 'em {0} min.', other: 'em {0} min.'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: 'há {0} h', other: 'há {0} h'),
      future: Plural(one: 'em {0} h', other: 'em {0} h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: 'há {0} dia', other: 'há {0} dias'),
      future: Plural(one: 'em {0} dia', other: 'em {0} dias'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: 'há {0} sem.', other: 'há {0} sem.'),
      future: Plural(one: 'em {0} sem.', other: 'em {0} sem.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: 'há {0} mês', other: 'há {0} meses'),
      future: Plural(one: 'em {0} mês', other: 'em {0} meses'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: 'há {0} ano', other: 'há {0} anos'),
      future: Plural(one: 'em {0} ano', other: 'em {0} anos'),
    ),
  },
);
