// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const roLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(
      one: 'acum {0} săptămână',
      few: 'acum {0} săptămâni',
      other: 'acum {0} de săptămâni',
    ),
    future: Plural(
      one: 'peste {0} săptămână',
      few: 'peste {0} săptămâni',
      other: 'peste {0} de săptămâni',
    ),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(
      one: 'acum {0} lună',
      few: 'acum {0} luni',
      other: 'acum {0} de luni',
    ),
    future: Plural(
      one: 'peste {0} lună',
      few: 'peste {0} luni',
      other: 'peste {0} de luni',
    ),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(
      one: 'acum {0} an',
      few: 'acum {0} ani',
      other: 'acum {0} de ani',
    ),
    future: Plural(
      one: 'peste {0} an',
      few: 'peste {0} ani',
      other: 'peste {0} de ani',
    ),
  ),
};
const roShort = TimeAgoPatterns(
  justNow: 'acum',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(
        one: 'acum {0} sec.',
        few: 'acum {0} sec.',
        other: 'acum {0} sec.',
      ),
      future: Plural(
        one: 'peste {0} sec.',
        few: 'peste {0} sec.',
        other: 'peste {0} sec.',
      ),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(
        one: 'acum {0} min.',
        few: 'acum {0} min.',
        other: 'acum {0} min.',
      ),
      future: Plural(
        one: 'peste {0} min.',
        few: 'peste {0} min.',
        other: 'peste {0} min.',
      ),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: 'acum {0} h', few: 'acum {0} h', other: 'acum {0} h'),
      future: Plural(
        one: 'peste {0} h',
        few: 'peste {0} h',
        other: 'peste {0} h',
      ),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(
        one: 'acum {0} zi',
        few: 'acum {0} zile',
        other: 'acum {0} de zile',
      ),
      future: Plural(
        one: 'peste {0} zi',
        few: 'peste {0} zile',
        other: 'peste {0} de zile',
      ),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(
        one: 'acum {0} săpt.',
        few: 'acum {0} săpt.',
        other: 'acum {0} săpt.',
      ),
      future: Plural(
        one: 'peste {0} săpt.',
        few: 'peste {0} săpt.',
        other: 'peste {0} săpt.',
      ),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(
        one: 'acum {0} lună',
        few: 'acum {0} luni',
        other: 'acum {0} de luni',
      ),
      future: Plural(
        one: 'peste {0} lună',
        few: 'peste {0} luni',
        other: 'peste {0} de luni',
      ),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(
        one: 'acum {0} an',
        few: 'acum {0} ani',
        other: 'acum {0} de ani',
      ),
      future: Plural(
        one: 'peste {0} an',
        few: 'peste {0} ani',
        other: 'peste {0} de ani',
      ),
    ),
  },
);
const roNarrow = TimeAgoPatterns(
  justNow: 'acum',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '-{0} s', few: '-{0} s', other: '-{0} s'),
      future: Plural(one: '+{0} s', few: '+{0} s', other: '+{0} s'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '-{0} m', few: '-{0} m', other: '-{0} m'),
      future: Plural(one: '+{0} m', few: '+{0} m', other: '+{0} m'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '-{0} h', few: '-{0} h', other: '-{0} h'),
      future: Plural(one: '+{0} h', few: '+{0} h', other: '+{0} h'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '-{0} zi', few: '-{0} zile', other: '-{0} zile'),
      future: Plural(one: '+{0} zi', few: '+{0} zile', other: '+{0} zile'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '-{0} săpt.', few: '-{0} săpt.', other: '-{0} săpt.'),
      future: Plural(one: '+{0} săpt.', few: '+{0} săpt.', other: '+{0} săpt.'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '-{0} lună', few: '-{0} luni', other: '-{0} luni'),
      future: Plural(one: '+{0} lună', few: '+{0} luni', other: '+{0} luni'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '-{0} an', few: '-{0} ani', other: '-{0} ani'),
      future: Plural(one: '+{0} an', few: '+{0} ani', other: '+{0} ani'),
    ),
  },
);
