// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const trLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: '{0} hafta önce', other: '{0} hafta önce'),
    future: Plural(one: '{0} hafta sonra', other: '{0} hafta sonra'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: '{0} ay önce', other: '{0} ay önce'),
    future: Plural(one: '{0} ay sonra', other: '{0} ay sonra'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: '{0} yıl önce', other: '{0} yıl önce'),
    future: Plural(one: '{0} yıl sonra', other: '{0} yıl sonra'),
  ),
};
const trShort = TimeAgoPatterns(
  justNow: 'şimdi',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} sn. önce', other: '{0} sn. önce'),
      future: Plural(one: '{0} sn. sonra', other: '{0} sn. sonra'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} dk. önce', other: '{0} dk. önce'),
      future: Plural(one: '{0} dk. sonra', other: '{0} dk. sonra'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} sa. önce', other: '{0} sa. önce'),
      future: Plural(one: '{0} sa. sonra', other: '{0} sa. sonra'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} gün önce', other: '{0} gün önce'),
      future: Plural(one: '{0} gün sonra', other: '{0} gün sonra'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} hf. önce', other: '{0} hf. önce'),
      future: Plural(one: '{0} hf. sonra', other: '{0} hf. sonra'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} ay önce', other: '{0} ay önce'),
      future: Plural(one: '{0} ay sonra', other: '{0} ay sonra'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} yıl önce', other: '{0} yıl önce'),
      future: Plural(one: '{0} yıl sonra', other: '{0} yıl sonra'),
    ),
  },
);
const trNarrow = TimeAgoPatterns(
  justNow: 'şimdi',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} sn. önce', other: '{0} sn. önce'),
      future: Plural(one: '{0} sn. sonra', other: '{0} sn. sonra'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} dk. önce', other: '{0} dk. önce'),
      future: Plural(one: '{0} dk. sonra', other: '{0} dk. sonra'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} sa. önce', other: '{0} sa. önce'),
      future: Plural(one: '{0} sa. sonra', other: '{0} sa. sonra'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} gün önce', other: '{0} gün önce'),
      future: Plural(one: '{0} gün sonra', other: '{0} gün sonra'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} hf. önce', other: '{0} hf. önce'),
      future: Plural(one: '{0} hf. sonra', other: '{0} hf. sonra'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} ay önce', other: '{0} ay önce'),
      future: Plural(one: '{0} ay sonra', other: '{0} ay sonra'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} yıl önce', other: '{0} yıl önce'),
      future: Plural(one: '{0} yıl sonra', other: '{0} yıl sonra'),
    ),
  },
);
