// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const urLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(one: '{0} ہفتہ پہلے', other: '{0} ہفتے پہلے'),
    future: Plural(one: '{0} ہفتہ میں', other: '{0} ہفتے میں'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(one: '{0} مہینہ پہلے', other: '{0} مہینے پہلے'),
    future: Plural(one: '{0} مہینہ میں', other: '{0} مہینے میں'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(one: '{0} سال پہلے', other: '{0} سال پہلے'),
    future: Plural(one: '{0} سال میں', other: '{0} سال میں'),
  ),
};
const urShort = TimeAgoPatterns(
  justNow: 'اب',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} سیکنڈ پہلے', other: '{0} سیکنڈ پہلے'),
      future: Plural(one: '{0} سیکنڈ میں', other: '{0} سیکنڈ میں'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} منٹ پہلے', other: '{0} منٹ پہلے'),
      future: Plural(one: '{0} منٹ میں', other: '{0} منٹ میں'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} گھنٹے پہلے', other: '{0} گھنٹے پہلے'),
      future: Plural(one: '{0} گھنٹے میں', other: '{0} گھنٹے میں'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} دن پہلے', other: '{0} دن پہلے'),
      future: Plural(one: '{0} دن میں', other: '{0} دنوں میں'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} ہفتے پہلے', other: '{0} ہفتے پہلے'),
      future: Plural(one: '{0} ہفتے میں', other: '{0} ہفتے میں'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} ماہ قبل', other: '{0} ماہ قبل'),
      future: Plural(one: '{0} ماہ میں', other: '{0} ماہ میں'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} سال پہلے', other: '{0} سال پہلے'),
      future: Plural(one: '{0} سال میں', other: '{0} سال میں'),
    ),
  },
);
const urNarrow = TimeAgoPatterns(
  justNow: 'اب',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(one: '{0} سیکنڈ پہلے', other: '{0} سیکنڈ پہلے'),
      future: Plural(one: '{0} سیکنڈ میں', other: '{0} سیکنڈ میں'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(one: '{0} منٹ پہلے', other: '{0} منٹ پہلے'),
      future: Plural(one: '{0} منٹ میں', other: '{0} منٹ میں'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(one: '{0} گھنٹہ پہلے', other: '{0} گھنٹے پہلے'),
      future: Plural(one: '{0} گھنٹے میں', other: '{0} گھنٹوں میں'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(one: '{0} دن پہلے', other: '{0} دن پہلے'),
      future: Plural(one: '{0} دن میں', other: '{0} دنوں میں'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(one: '{0} ہفتہ پہلے', other: '{0} ہفتے پہلے'),
      future: Plural(one: '{0} ہفتہ میں', other: '{0} ہفتے میں'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(one: '{0} ماہ پہلے', other: '{0} ماہ پہلے'),
      future: Plural(one: '{0} ماہ میں', other: '{0} ماہ میں'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(one: '{0} سال پہلے', other: '{0} سال پہلے'),
      future: Plural(one: '{0} سال میں', other: '{0} سال میں'),
    ),
  },
);
