// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const viLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(other: '{0} tuần trước'),
    future: Plural(other: 'sau {0} tuần nữa'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(other: '{0} tháng trước'),
    future: Plural(other: 'sau {0} tháng nữa'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(other: '{0} năm trước'),
    future: Plural(other: 'sau {0} năm nữa'),
  ),
};
const viShort = TimeAgoPatterns(
  justNow: 'bây giờ',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0} giây trước'),
      future: Plural(other: 'sau {0} giây nữa'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0} phút trước'),
      future: Plural(other: 'sau {0} phút nữa'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0} giờ trước'),
      future: Plural(other: 'sau {0} giờ nữa'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0} ngày trước'),
      future: Plural(other: 'sau {0} ngày nữa'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0} tuần trước'),
      future: Plural(other: 'sau {0} tuần nữa'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0} tháng trước'),
      future: Plural(other: 'sau {0} tháng nữa'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0} năm trước'),
      future: Plural(other: 'sau {0} năm nữa'),
    ),
  },
);
const viNarrow = TimeAgoPatterns(
  justNow: 'bây giờ',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0} giây trước'),
      future: Plural(other: 'sau {0} giây nữa'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0} phút trước'),
      future: Plural(other: 'sau {0} phút nữa'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0} giờ trước'),
      future: Plural(other: 'sau {0} giờ nữa'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0} ngày trước'),
      future: Plural(other: 'sau {0} ngày nữa'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0} tuần trước'),
      future: Plural(other: 'sau {0} tuần nữa'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0} tháng trước'),
      future: Plural(other: 'sau {0} tháng nữa'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0} năm trước'),
      future: Plural(other: 'sau {0} năm nữa'),
    ),
  },
);
