// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const zhLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(other: '{0}周前'),
    future: Plural(other: '{0}周后'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(other: '{0}个月前'),
    future: Plural(other: '{0}个月后'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(other: '{0}年前'),
    future: Plural(other: '{0}年后'),
  ),
};
const zhShort = TimeAgoPatterns(
  justNow: '现在',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0}秒前'),
      future: Plural(other: '{0}秒后'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0}分钟前'),
      future: Plural(other: '{0}分钟后'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0}小时前'),
      future: Plural(other: '{0}小时后'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0}天前'),
      future: Plural(other: '{0}天后'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0}周前'),
      future: Plural(other: '{0}周后'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0}个月前'),
      future: Plural(other: '{0}个月后'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0}年前'),
      future: Plural(other: '{0}年后'),
    ),
  },
);
const zhNarrow = TimeAgoPatterns(
  justNow: '现在',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0}秒前'),
      future: Plural(other: '{0}秒后'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0}分钟前'),
      future: Plural(other: '{0}分钟后'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0}小时前'),
      future: Plural(other: '{0}小时后'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0}天前'),
      future: Plural(other: '{0}天后'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0}周前'),
      future: Plural(other: '{0}周后'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0}个月前'),
      future: Plural(other: '{0}个月后'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0}年前'),
      future: Plural(other: '{0}年后'),
    ),
  },
);
