// Generated by tool/cldr/generate.dart from CLDR 48.2.2. Do not edit.
// ignore_for_file: public_member_api_docs

import '../../messages/time_ago_locale.dart';
import '../../time_unit.dart';

const zhTwLongUnits = <TimeUnit, RelativePatterns>{
  TimeUnit.week: RelativePatterns(
    past: Plural(other: '{0} 週前'),
    future: Plural(other: '{0} 週後'),
  ),
  TimeUnit.month: RelativePatterns(
    past: Plural(other: '{0} 個月前'),
    future: Plural(other: '{0} 個月後'),
  ),
  TimeUnit.year: RelativePatterns(
    past: Plural(other: '{0} 年前'),
    future: Plural(other: '{0} 年後'),
  ),
};
const zhTwShort = TimeAgoPatterns(
  justNow: '現在',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0} 秒前'),
      future: Plural(other: '{0} 秒後'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0} 分鐘前'),
      future: Plural(other: '{0} 分鐘後'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0} 小時前'),
      future: Plural(other: '{0} 小時後'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0} 天前'),
      future: Plural(other: '{0} 天後'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0} 週前'),
      future: Plural(other: '{0} 週後'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0} 個月前'),
      future: Plural(other: '{0} 個月後'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0} 年前'),
      future: Plural(other: '{0} 年後'),
    ),
  },
);
const zhTwNarrow = TimeAgoPatterns(
  justNow: '現在',
  units: {
    TimeUnit.second: RelativePatterns(
      past: Plural(other: '{0} 秒前'),
      future: Plural(other: '{0} 秒後'),
    ),
    TimeUnit.minute: RelativePatterns(
      past: Plural(other: '{0} 分鐘前'),
      future: Plural(other: '{0} 分鐘後'),
    ),
    TimeUnit.hour: RelativePatterns(
      past: Plural(other: '{0} 小時前'),
      future: Plural(other: '{0} 小時後'),
    ),
    TimeUnit.day: RelativePatterns(
      past: Plural(other: '{0} 天前'),
      future: Plural(other: '{0} 天後'),
    ),
    TimeUnit.week: RelativePatterns(
      past: Plural(other: '{0} 週前'),
      future: Plural(other: '{0} 週後'),
    ),
    TimeUnit.month: RelativePatterns(
      past: Plural(other: '{0} 個月前'),
      future: Plural(other: '{0} 個月後'),
    ),
    TimeUnit.year: RelativePatterns(
      past: Plural(other: '{0} 年前'),
      future: Plural(other: '{0} 年後'),
    ),
  },
);
